Modify .github/workflows/ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,11 +31,10 @@ jobs:
         uses: actions/cache@v3
         with:
           path: vendor/bundle
-          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
+          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-v1
           restore-keys: |
-            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
-            ${{ runner.os }}--gems
-            ${{ runner.os }}-
+            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-v1
+            ${{ runner.os }}-gems-v1
 
       - name: Install dependencies
         run: |
@@ -49,24 +48,16 @@ jobs:
         run: sudo apt-get install -y postgresql-14
 
       - name: Start PostgreSQL
-        run: sudo service postgresql start
-
-      - name: Check PostgreSQL status
-        run: sudo service postgresql status
-
-      - name: Check PostgreSQL logs for errors
-        run: tail -n 100 /var/log/postgresql/postgresql-14-main.log | grep "FATAL" || true
-
-      - name: List PostgreSQL log directory
-        run: ls -l /var/log/postgresql
-
-      - name: Wait for PostgreSQL to be ready
         run: |
+          sudo service postgresql start
           until pg_isready -h localhost -p 5432; do
             echo "Waiting for PostgreSQL..."
             sleep 1
           done
           echo "PostgreSQL is ready"
+
+      - name: Check PostgreSQL status
+        run: sudo service postgresql status || echo "PostgreSQL status check failed"
 
       - name: Update pg_hba.conf for md5 authentication
         run: |
@@ -74,17 +65,17 @@ jobs:
           sudo sed -i "s/ident/md5/g" /etc/postgresql/14/main/pg_hba.conf
           sudo sed -i "s/scram-sha-256/md5/g" /etc/postgresql/14/main/pg_hba.conf
           sudo service postgresql restart
-
-      - name: Check postgesql restart
-        run: |
           until pg_isready -h localhost -p 5432; do
-            echo "Waiting for PostgreSQL..."
+            echo "Waiting for PostgreSQL after restart..."
             sleep 1
           done
           echo "PostgreSQL is ready"
 
-      - name: Check Update md5 authentication
-        run: sudo cat /etc/postgresql/14/main/pg_hba.conf
+      - name: Set PostgreSQL superuser password
+        run: |
+          psql -U postgres -c "ALTER USER postgres WITH PASSWORD '${{ secrets.POSTGRES_PASSWORD }}';"
+        env:
+          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
 
       - name: Set up PostgreSQL user and database
         run: |
@@ -96,6 +87,8 @@ jobs:
             psql -U postgres -c "CREATE DATABASE ${{ secrets.POSTGRES_DB }} OWNER ${{ secrets.POSTGRES_USER }};"
           fi
           psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.POSTGRES_DB }} TO ${{ secrets.POSTGRES_USER }};"
+        env:
+          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
 
       - name: Run database migrations
         run: bundle exec rails db:migrate RAILS_ENV=test
@@ -108,11 +101,16 @@ jobs:
 
       - name: Log in to GitHub Container Registry
         run: |
-          set -e
-          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin || {
-            echo "Docker login failed"; exit 1;
-          }
-          echo "Docker login successful"
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+          if [ $? -ne 0 ]; then
+            echo "Retrying Docker login..."
+            sleep 5
+            docker login ghcr.io -u ${{ github.actor }} --password-stdin
+            if [ $? -ne 0 ]; then
+              echo "Docker login failed after retry."
+              exit 1
+            fi
+          fi
 
       - name: Determine Docker tag
         run: |
@@ -120,6 +118,7 @@ jobs:
             TAG="latest"
           else
             TAG="${{ github.sha }}"
+
           fi
 
           if [[ -z "${TAG}" ]]; then
@@ -133,14 +132,14 @@ jobs:
       - name: Check if Dockerfile or related files changed
         run: |
           set -e
-          git fetch origin main || true
-          if [[ -z ${TAG} ]]; then
+          git fetch origin main
+          if [[ -z "${TAG}" ]]; then
             echo "TAG is not set, exiting."
             exit 1
           else
             if git diff --name-only origin/main...HEAD | grep -E "(Dockerfile|compose.yaml)" --exit-code; then
-              docker build -t ghcr.io/vinylhousegarage/device_expansion:$TAG .
-              docker push ghcr.io/vinylhousegarage/device_expansion:$TAG
+              docker build -t ghcr.io/vinylhousegarage/device_expansion:"${TAG}" .
+              docker push ghcr.io/vinylhousegarage/device_expansion:"${TAG}"
             else
               echo "No changes in Dockerfile, skipping build and push."
             fi
@@ -164,6 +163,7 @@ jobs:
         run: |
           set -e
           RESPONSE=$(curl -X POST \
+          --verbose \
           -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
           -H "Content-Type: application/json" \
           -d '{"clearCache":false}' \
@@ -174,24 +174,28 @@ jobs:
             exit 1
           fi
 
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
       - name: Get latest Render Deploy ID and Status
         run: |
           set -e
           RESPONSE=$(curl -X GET \
+          --verbose \
           "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
           -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
           -H "Content-Type: application/json" --fail --show-error)
 
-          LATEST_DEPLOY=$(echo $RESPONSE | jq -r '. | sort_by(.createdAt) | last')
-          if [[ -z "LATEST_DEPLOY" ]]; then
+          LATEST_DEPLOY=$(echo "$RESPONSE" | jq -r '. | sort_by(.createdAt) | last')
+          if [[ -z "$LATEST_DEPLOY" ]]; then
             echo "Failed to retrieve the latest deploy"
             exit 1
           fi
 
-          RENDER_DEPLOY_ID=$(echo $LATEST_DEPLOY | jq -r '.id')
-          STATUS=$(echo $LATEST_DEPLOY | jq -r '.status')
+          RENDER_DEPLOY_ID=$(echo "$LATEST_DEPLOY" | jq -r '.id')
+          STATUS=$(echo "$LATEST_DEPLOY" | jq -r '.status')
 
-          if [[ -z "RENDER_DEPLOY_ID" ]]; then
+          if [[ -z "$RENDER_DEPLOY_ID" ]]; then
             echo "Failed to extract deployment details"
             exit 1
           fi
@@ -202,13 +206,14 @@ jobs:
             echo "Deployment failed with status: $STATUS"
             exit 1
           else
-            echo "Deployment succeeded"
+            echo "Deployment succeeded with status: $STATUS"
           fi
 
       - name: Run migration on Render
         run: |
           set -e
           curl -X POST \
+          --verbose \
           -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
           -H "Content-Type: application/json" \
           -d '{"command": "rails db:migrate"}' \
@@ -218,6 +223,7 @@ jobs:
         run: |
           set -e
           curl -X POST \
+          --verbose \
           -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
           -H "Content-Type: application/json" \
           -d '{"command": "rails db:seed"}' \
@@ -232,6 +238,7 @@ jobs:
           else
             echo "Render Deploy ID: $RENDER_DEPLOY_ID"
             curl -X GET \
+            --verbose \
             "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$RENDER_DEPLOY_ID/logs" \
             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
             -H "Content-Type: application/json" --fail --show-error
