Add error handling to Set up database

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -116,8 +116,12 @@ jobs:
       # データベースをセットアップ
       - name: Set up database
         run: |
-          set -e
-          sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname=${{ secrets.POSTGRES_DB }}" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.POSTGRES_DB }} WITH OWNER ${{ secrets.POSTGRES }};"
+          if ! sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${{ secrets.POSTGRES_DB }}'" | grep -q 1; then
+            echo "Database not found, creating it..."
+            sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.POSTGRES_DB }} WITH OWNER ${{ secrets.POSTGRES }};"
+          else
+            echo "Database already exists."
+          fi
 
       # POSTGRES_DB を生成
       - name: Run Create database
