Merged separate CI and CD workflows into cicd.yml to enhance workflow efficiency

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -1,6 +1,9 @@
-name: CI
+name: CI/CD Workflow
 
 on:
+  push:
+    branches:
+      - main
   pull_request:
     branches:
       - main
@@ -88,7 +91,7 @@ jobs:
         run: |
           set -e
           sudo apt-get update
-          sudo apt-get install -y libpq-dev || echo "Failed to install libpq-dev"
+          sudo apt-get install -y libpq-dev
           bundle config set path 'vendor/bundle'
           bundle install --jobs 4 --retry 3
 
@@ -242,3 +245,105 @@ jobs:
           RAILS_ENV: production
           SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
         run: bundle exec rails assets:precompile
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    env:
+      RAILS_ENV: production
+
+    steps:
+      # リモートリポジトリをチェックアウト
+      - name: Check out the repository
+        uses: actions/checkout@v3
+
+      # Render API へデプロイ
+      # Render API からのレスポンスを確認
+      - name: Trigger Render Deployment
+        run: |
+          set -e
+          POST_RESPONSE=$(curl -X POST \
+          --verbose \
+          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
+          -H "Content-Type: application/json" \
+          -d '{"clearCache": true}' \
+          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys --fail --show-error)
+
+          if [[ -z "$POST_RESPONSE" ]]; then
+            echo "Failed to trigger deployment for service ID: ${{ secrets.RENDER_SERVICE_ID }}"
+            exit 1
+          else
+            echo "Deployment POST response:$POST_RESPONSE"
+          fi
+
+      # 最大180回の反復を設定
+      # Render API からデプロイ情報を取得
+      # 変数GET_DEPROY_RESPONSE が空ではないか確認
+      # レスポンス全体を表示してデバッグ情報を確認
+      # 最新のデプロイ情報を取得
+      # 変数LATEST_DEPLOY が空ではないか確認
+      # デプロイID を取得
+      # 変数RENDER_DEPLOY_ID が空ではないか確認
+      # 変数RENDER_DEPLOY_ID を GITHUB_ENV に格納
+      # デプロイステータスを取得
+      # 変数RENDER_DEPLOY_STATUS が空でないか確認
+      # ステータスを判定
+      # 10秒待機しステータスの判定を反復
+      - name: Check Render Deployment Status
+        run: |
+          set -e
+
+          for i in {1..180}; do
+
+            GET_DEPLOY_RESPONSE=$(curl -X GET \
+            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
+            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
+            -H "Content-Type: application/json" --fail --show-error)
+
+            if [[ -z "$GET_DEPLOY_RESPONSE" ]]; then
+              echo "Failed to retrieve deployment information"
+              exit 1
+            fi
+
+            echo "$GET_DEPLOY_RESPONSE" | jq '.'
+
+            LATEST_DEPLOY=$(echo "$GET_DEPLOY_RESPONSE" | jq -r 'map(.deploy) | sort_by(.createdAt) | last')
+
+            if [[ -z "$LATEST_DEPLOY" ]]; then
+              echo "Failed to retrieve the latest deploy"
+              exit 1
+            fi
+
+            RENDER_DEPLOY_ID=$(echo "$LATEST_DEPLOY" | jq -r '.id')
+            if [[ -z "$RENDER_DEPLOY_ID" ]]; then
+              echo "Failed to extract deployment details"
+              exit 1
+            else
+              echo "Render Deploy ID: $RENDER_DEPLOY_ID"
+              echo "RENDER_DEPLOY_ID=$RENDER_DEPLOY_ID" >> $GITHUB_ENV
+            fi
+
+            RENDER_DEPLOY_STATUS=$(echo "$LATEST_DEPLOY" | jq -r '.status')
+            if [[ -z "$RENDER_DEPLOY_STATUS" ]]; then
+              echo "Failed to retrieve deployment status"
+              exit 1
+            elif [[ "$RENDER_DEPLOY_STATUS" == "build_failed" ]]; then
+              echo "Deployment build_failed!"
+              exit 1
+            elif [[ "$RENDER_DEPLOY_STATUS" == "update_failed" ]]; then
+              echo "Deployment update_failed!"
+              exit 1
+            elif [[ "$RENDER_DEPLOY_STATUS" == "canceled" ]]; then
+              echo "Deployment canceled!"
+              exit 1
+            elif [[ "$RENDER_DEPLOY_STATUS" == "live" ]]; then
+              echo "Deployment live!"
+              exit 0
+            fi
+
+            sleep 10
+          done
+
+          echo "Deployment is still in progress after 30 minutes. Exiting."
+          echo "Final Deployment Status: $RENDER_DEPLOY_STATUS"
+          exit 1
